packages: []
overrides:
  '@types/node': 20.11.5
  '@vercel/nft': ^0.27.4
  vite: ^6.2.6
catalog:
  '@ai-sdk/vue': '>=1.2.5'
  '@antfu/nip': ^0.1.0
  '@josephanson/nuxt-ai': 0.1.6
  '@tailwindcss/postcss': ^0.0.0

  pncat: ^0.2.0

catalogs:
  build:
    '@antfu/eslint-config': ^4.12.0
    '@nuxt/eslint': ^1.3.0
    '@nuxt/fonts': ^0.11.2
    '@nuxt/icon': ^1.12.0
    '@nuxt/image': ^1.10.0
    '@nuxt/scripts': ^0.11.6
    '@nuxthub/core': ^0.8.27
    '@nuxtjs/color-mode': ^3.5.2
    '@nuxtjs/seo': ^3.0.3
    '@pinia/nuxt': ^0.11.0
    '@prisma/client': ^6.7.0
    '@prisma/nuxt': ^0.3.0
    '@sentry/nuxt': ^9.15.0
    '@tailwindcss/vite': ^4.1.5
    '@vee-validate/zod': ^4.15.0
    '@vite-pwa/nuxt': ^1.0.0
    '@vueuse/nuxt': ^13.1.0
    '@vueuse/router': ^13.1.0
    discord-api-types: ^0.38.3
    eslint: ^9.26.0
    eslint-config-prettier: ^10.1.5
    eslint-plugin-format: ^1.0.1
    eslint-plugin-package-json: ^0.31.0
    eslint-plugin-prettier: ^5.4.0
    nuxt: ^3.17.2
    nuxt-authorization: ^0.3.4
    prisma: ^6.7.0
    prisma-json-types-generator: ^3.3.1
    reka-ui: ^2.2.0
    shadcn-nuxt: 2.1.0
    stale-dep: ^0.8.2
    tw-animate-css: ^1.2.9
    zod: ^3.24.4
  dev:
    '@commitlint/cli': ^19.8.0
    '@commitlint/config-conventional': ^19.8.0
    '@discordjs/collection': ^2.1.1
    '@discordjs/core': ^2.1.0
    '@sapphire/bitfield': ^1.2.4
    '@sapphire/prettier-config': ^2.0.0
    '@sapphire/ratelimits': ^2.4.11
    '@sapphire/result': ^2.7.2
    '@sapphire/snowflake': ^3.5.5
    '@sapphire/time-utilities': ^1.7.14
    '@sapphire/utilities': ^3.18.2
    '@tailwindcss/typography': ^0.5.16
    daisyui: 5.0.35
    husky: ^9.1.7
    lint-staged: ^15.5.1
    nuxt-auth-utils: ^0.5.20
    playwright: ^1.52.0
    prettier: ^3.5.3
    prettier-plugin-css-order: ^2.1.2
    prettier-plugin-tailwindcss: ^0.6.11
    std-env: ^3.9.0
    tailwindcss: ^4.1.5
    typescript: ~5.8.3
    vue-tsc: 2.2.10
  frontend:
    '@vueuse/core': ^13.1.0
    clsx: ^2.1.1
    colortranslator: ^4.1.0
    consola: ^3.4.2
    fuse.js: ^7.1.0
    import-in-the-middle: ^1.13.1
    markdown-it-anchor: ^9.2.0
    pinia: ^3.0.2
    tailwind-merge: ^3.2.0
    tailwind-variants: ^1.0.0
    utility-types: ^3.11.0
    vue-markdown-render: ^2.2.1
    vue-sonner: ^1.3.2
  icons:
    '@iconify-json/heroicons': ^1.2.2
    '@iconify-json/ic': ^1.2.2
    '@iconify-json/lucide': ^1.2.40
    '@iconify-json/ph': ^1.2.2
allowedDeprecatedVersions:
  - glob: 7.2.3
  - sourcemap-codec: 1.4.8
  - inflight: 1.0.6
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - esbuild
  - prisma
  - sharp
  - vue-demi
peerDependencyRules:
  allowedVersions:
    inflight: 1.0.6
    typescript: 5.8.3
    vue-tsc: ^2.2.10
