packages: []
overrides:
    '@types/node': 20.11.5
    '@vercel/nft': ^0.27.4
    vite: ^6.3.5
catalogs:
    build:
        '@tailwindcss/vite': ^4.1.8
        '@vite-pwa/nuxt': ^1.0.3
    cli:
        pncat: ^0.2.4
        taze: ^19.1.0
    dev:
        '@ai-sdk/vue': '>=1.2.12'
        '@antfu/nip': ^0.1.0
        '@cloudflare/vite-plugin': ^1.7.5
        '@discordjs/collection': ^2.1.1
        '@discordjs/core': ^2.1.0
        '@nuxt/fonts': ^0.11.4
        '@nuxt/image': ^1.10.0
        '@nuxt/scripts': ^0.11.8
        '@nuxthub/core': ^0.8.27
        '@nuxtjs/seo': ^3.0.3
        '@sapphire/bitfield': ^1.2.4
        '@sapphire/ratelimits': ^2.4.11
        '@sapphire/result': ^2.7.2
        '@sapphire/snowflake': ^3.5.5
        '@sapphire/time-utilities': ^1.7.14
        '@sapphire/utilities': ^3.18.2

        daisyui: 5.0.35
        discord-api-types: ^0.38.11
        nuxt-auth-utils: ^0.5.20
        simple-git: ^3.28.0
        std-env: ^3.9.0
        typescript: ~5.8.3
        vue-tsc: 2.2.10
        wrangler: ^4.19.1
    frontend:
        '@pinia/nuxt': ^0.11.1
        pinia: ^3.0.3
        reka-ui: ^2.3.0
    icons:
        '@iconify-json/heroicons': ^1.2.2
        '@iconify-json/ic': ^1.2.2
        '@iconify-json/lucide': ^1.2.46
        '@iconify-json/ph': ^1.2.2
        '@nuxt/icon': ^1.13.0
    lint:
        '@antfu/eslint-config': ^4.14.1
        '@commitlint/cli': ^19.8.1
        '@commitlint/config-conventional': ^19.8.1
        '@nuxt/eslint': ^1.4.1
        '@sapphire/prettier-config': ^2.0.0
        eslint: ^9.28.0
        eslint-config-prettier: ^10.1.5
        eslint-plugin-format: ^1.0.1
        eslint-plugin-package-json: ^0.31.0
        eslint-plugin-prettier: ^5.4.1
        husky: ^9.1.7
        lint-staged: ^15.5.2
        prettier: ^3.5.3
        prettier-plugin-css-order: ^2.1.2
        prettier-plugin-tailwindcss: ^0.6.12
    markdown:
        markdown-it-anchor: ^9.2.0
        vue-markdown-render: ^2.2.1
    node:
        consola: ^3.4.2
    prod:
        '@josephanson/nuxt-ai': 0.1.6
        '@nuxtjs/color-mode': ^3.5.2
        '@prisma/client': ^6.9.0
        '@prisma/nuxt': ^0.3.0
        '@shelve/cli': ^4.1.6
        colortranslator: ^4.1.0
        fuse.js: ^7.1.0
        import-in-the-middle: ^1.14.0
        nuxt: ^3.17.5
        nuxt-authorization: ^0.3.4
        prisma: ^6.9.0
        prisma-json-types-generator: ^3.4.2
        shadcn-nuxt: 2.1.0
        stale-dep: ^0.8.2
        tailwind-variants: ^1.0.0
        utility-types: ^3.11.0
        vue-sonner: ^2.0.1
    style:
        '@tailwindcss/typography': ^0.5.16
        tailwind-merge: ^3.3.0
        tailwindcss: ^4.1.8
        tw-animate-css: ^1.3.4
    test:
        playwright: ^1.52.0
    utils:
        '@vee-validate/zod': ^4.15.0
        '@vueuse/core': ^13.3.0
        '@vueuse/nuxt': ^13.3.0
        '@vueuse/router': ^13.3.0
        clsx: ^2.1.1
        zod: ^3.25.55
allowedDeprecatedVersions:
    - glob: 7.2.3
    - sourcemap-codec: 1.4.8
    - inflight: 1.0.6
onlyBuiltDependencies:
    - '@parcel/watcher'
    - '@prisma/client'
    - '@prisma/engines'

    - esbuild
    - prisma
    - sharp
    - vue-demi
peerDependencyRules:
    allowedVersions:
        inflight: 1.0.6
        typescript: 5.8.3
        vue-tsc: ^2.2.10
